auto: true
server: true
artist_name: "Dana Billings"
artist_email: "iydrums@yahoo.com"
artist_phone: "607.279.4251"
artist_bio: "Musician, Recording Engineer, Producer"
soundcloud_username: "dana-billings"
soundcloud_user_id: "697067"
soundcloud_consumer_key: "3cd3a5dad22fbbf8797ee416abee8434"

