auto: true
artist_name: "Dana Billings"
artist_email: "iydrums@yahoo.com"
artist_phone: "607.279.4251"
artist_bio: "Dana Billings makes, mixes, and masters music."
soundcloud_username: "dana-billings"
#soundcloud_user_id: "697067"
soundcloud_user_id: "15856496"
soundcloud_consumer_key: "1c064be0110a6d80ac2ff60a7dd22058"

